version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - npm install
  post_build:
    commands:
      - mkdir build-output
      - cp -R ./ build-output
artifacts:
  files:
    - build-output/**/*
